name: run-test-df

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - run: pip install pandas

      - run: python test_dataframe.py

      - name: Commit CSV
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add adunits.csv
          git commit -m "update csv"
          git push
